services:
  web:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/potato_api
      - REDIS_URL=redis://redis:6379/0
      - RATELIMIT_STORAGE_URL=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/app
    command:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:8000",
        "--workers",
        "4",
        "--reload",
        "app.main:create_app()",
      ]

  worker:
    build: ./api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/potato_api
      - REDIS_URL=redis://redis:6379/0
      - RATELIMIT_STORAGE_URL=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/app
    command: ["celery", "-A", "app.celery_app", "worker", "--loglevel=info"]

  beat:
    build: ./api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/potato_api
      - REDIS_URL=redis://redis:6379/0
      - RATELIMIT_STORAGE_URL=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/app
      - beat_schedule:/tmp
    command:
      [
        "celery",
        "-A",
        "app.celery_app",
        "beat",
        "--loglevel=info",
        "--schedule=/tmp/celerybeat-schedule",
      ]

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: potato_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  beat_schedule:
